# sign in at https://travis-ci.org/#
#
# https://github.com/travis-ci/travis-ci/issues/2197#issuecomment-41177752
# before_install:
#  - brew update
#  - brew upgrade xctool
#
# http://docs.travis-ci.com/user/languages/objective-c/
language: objective-c
xcode_sdk:
#  - iphoneos         CodeSign error: code signing is required for product type 'Unit Test Bundle' in SDK 'iOS 8.1'
#  - iphoneos8.1      CodeSign error: code signing is required for product type 'Unit Test Bundle' in SDK 'iOS 8.1'
  - iphonesimulator
xcode_project: MROGeometry.xcodeproj
xcode_scheme: MROGeometry
